services:
  backend:
    image: sivera/sivera:backend
    pull_policy: always
    ports:
      - "8000:8000"
    restart: always
    environment:
      - GEMINI_API_KEY=REDACTED_GEMINI_API_KEY
      - GROQ_API_KEY=REDACTED_GROQ_API_KEY
      - OPENAI_API_KEY=REDACTED_OPENAI_API_KEY
      - DAILY_API_KEY=REDACTED_DAILY_API_KEY
      - DEEPGRAM_API_KEY=REDACTED_DEEPGRAM_API_KEY
      - ELEVENLABS_API_KEY=REDACTED_ELEVENLABS_API_KEY
      - FAL_API_KEY=REDACTED_FAL_API_KEY
      - ELEVENLABS_VOICE_ID=TX3LPaxmHKxFdv7VOQHJ
      - RIME_API_KEY=REDACTED_RIME_API_KEY
      - RIME_VOICE_ID=wildflower
      - GOOGLE_CREDENTIALS_PATH=/Users/gsnmithra/.builds/Hexagon-A/backend/credentials.json
      - GOOGLE_VOICE_ID=en-US-Chirp3-HD-Achernar
      - LLM_MODEL=gemini-2.5-pro
      - LLM_PROVIDER=google
      - TTS_PROVIDER=google
      - SUPABASE_URL=https://gdivpjirohbxantnnmmg.supabase.co
      - SUPABASE_KEY=REDACTED_SUPABASE_KEY
      - RELOAD=false

  frontend:
    image: sivera/sivera:frontend
    pull_policy: always
    environment:
      - NEXT_PUBLIC_PIPECAT_BASE_URL=https://core.sivera.io
      - NEXT_PUBLIC_SITE_URL=https://app.sivera.io
      - NEXT_PUBLIC_SIVERA_BACKEND_URL=https://api.sivera.io
      - NEXT_PUBLIC_CORE_BACKEND_URL=https://core.sivera.io
    ports:
      - "3000:3000"
    restart: always
