services:
  flowterview-backend:
    image: sivera/sivera:recruiter-backend
    pull_policy: always
    ports:
      - "8010:8010"
    restart: always
    env_file:
      - .env.recruiter

  flowterview-app:
    image: sivera/sivera:recruiter-frontend
    pull_policy: always
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env.recruiter
