services:
  backend:
    image: sivera/sivera:backend
    pull_policy: always
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env.candidate

  frontend:
    image: sivera/sivera:frontend
    pull_policy: always
    env_file:
      - .env.candidate
    ports:
      - "3000:3000"
    restart: always
