repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: v0.6.3
    hooks:
      - id: uv-lock
        name: Lock UV dependencies
        files: ^.*/?pyproject.toml$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8
    hooks:
      - id: ruff
        name: Run Ruff linter
        args: [--fix, --ignore=E501, B904, ARG001, ARG002, SIM102, SIM103]
        types: [python]

      - id: ruff-format
        name: Run Ruff formatter
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=1000"]
